language: python
python:
    - 2.7
# command to install dependencies
install:
    - pip install -r requirements.txt -r requirements-dev.txt
# command to run tests
script:
    - py.test -vv --cov-report term --cov dump2polarion
after_success:
    - coveralls
